### ISSUE TITLE
Initialization configuration question: linking IGVNav to IGV on Linux

### ISSUE THREAD

**Issue by moldach** [griffithlab/igvnav#10]
I've tried to follow the step-by-step guide to setting up IGV and IGVNav but the two don't seem to be _talking_ to each other on CentOS-7.

1) I load IGV with the reference genome and track
2) I open IGVNav and load a CSV file

Now I can see the IGVNav interface correctly but when I hit "**Go**" IGV interface does not navigate to the coordinates on IGVNav interface.

Is there some file I need to edit for `PATH` to IGV? To be clear I'm using IGV I downloaded (I don't believe IGV came bundled with this APP, did it?)

**Comment by moldach** [comment]
Tried loading a new input file today and now I'm getting an error I didn't see before:

Trying again with three from the manuscript in the demo made into a `.csv` file:

```
chr	start	stop	ref	var	call	tags	notes
10	26174201	26174201	C	A			
14	44505849	44505849	A	G			
3	67004225	67004225	T	C
```

This is the error I see when trying to load the input in `IGVNav` if this helps:

```
$ python ~/bin/IGVNav.app/Contents/Resources/IGVNav.py
/export/home/moldach/bin/IGVNav.app/Contents/Resources/IGVNav.py:128: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_FILE_OPEN, self.OnOpen)
/export/home/moldach/bin/IGVNav.app/Contents/Resources/IGVNav.py:129: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_FILE_SAVE, self.OnSave)
/export/home/moldach/bin/IGVNav.app/Contents/Resources/IGVNav.py:130: wxPyDeprecationWarning: Call to deprecated item __call__. Use :meth:`EvtHandler.Bind` instead.
  wx.EVT_MENU(self, ID_FILE_EXIT, self.OnQuit)

(IGVNav.py:29340): GVFS-RemoteVolumeMonitor-WARNING **: 10:20:17.349: remote volume monitor with dbus name org.gtk.vfs.GoaVolumeMonitor is not supported

(IGVNav.py:29340): Gtk-WARNING **: 10:20:17.622: Failed to measure available space: Error getting filesystem info for /media/lexar: Transport endpoint is not connected
Traceback (most recent call last):
  File "/export/home/moldach/bin/IGVNav.app/Contents/Resources/IGVNav.py", line 583, in <module>
    main(sys.argv)
  File "/export/home/moldach/bin/IGVNav.app/Contents/Resources/IGVNav.py", line 577, in main
    rw.OnOpen(None)
  File "/export/home/moldach/bin/IGVNav.app/Contents/Resources/IGVNav.py", line 421, in OnOpen
    bed_file.load()
  File "/export/home/moldach/bin/IGVNav.app/Contents/Resources/IGVNav.py", line 459, in load
    int(row[1])
IndexError: list index out of range

```
